### PR TITLE
Bring back centos8 as centos8stream

### PR DESCRIPTION
**Pull request by eRadical**
Bring back CentOS Stream 8

### CODE REVIEW

**Comment by sivel** [comment]
I don't think we need to maintain this here.  It can be maintained anywhere, and users can decide to use it if they want, without official core team backing.

Maybe a community repo can be maintained of extra container images, and an associated docker hub or quay account can be used for hosting them.

**Comment by eRadical** [comment]
- Why not?
- What changed?
- What is different from Fedora or Ubuntu or OpenSuse?

It used to be: Fedora » RHEL » CentOS.
Now it's going to be: Fedora » CentOS Stream » RHEL.

CentOS Stream will be way more stable than Fedora.
It's weird not having CentOS Stream but still having Fedora.

The OSS community took the disappearance of CentOS really bad... not supporting CentOS Stream only encourages FUD. By not supporting CentOS Stream you confirm the rumors that RedHat will let it die.

If it's about maintaining this image (and the upcoming CentOS Stream version) - I'll make it a habit to maintain it.

**Comment by eRadical** [comment]
Already discussed this at https://github.com/ansible-collections/news-for-maintainers/discussions/4

Right now all Ansible & many (if not all) ansible-collections are dropping CentOS support instead of moving to CentOS Stream.
This means Ansible will not be tested and supported on CentOS Stream!
Which really looks bad!

**Comment by eRadical** [comment]
> We get nothing out of having CentOS test containers

Are you saying CentOS and/or CentOS Stream is dead!

**Comment by sivel** [comment]
> Are you saying CentOS and/or CentOS Stream is dead!

Please.  No one ever said that.  Keep trying to create problems.  I won't participate in the argument you are trying to trick people into.

**Comment by eRadical** [comment]
I didn't delete CentOS from this repo!
I'm trying to add it back!

**Comment by eRadical** [comment]
Let's try it another way:

Why not ditch Fedora container in favor of CentOS Stream?...

In all the articles RH published it said "CentOS Stream" will be more stable than Fedora.

I would totally understand that!

**Comment by eRadical** [comment]
Here is a longer discussion: https://github.com/ansible-collections/news-for-maintainers/discussions/4

**Comment by sivel** [comment]
We've had the time to have a lot of conversations about this over the past week.  In the end, the Core team has decided to continue _**not**_ testing CentOS Stream in our CI matrix.  By extension of this declaration, we are also not going to maintain a CentOS Stream image in this repository.  This decision has nothing to do with CentOS, and purely with evaluating whether our CI and testing methodologies benefit from adding these test targets.

**Pull request closed without merging**
