### PR TITLE
Add alpine3 test container

### PR DESCRIPTION
**Pull request by sivel**
This PR adds an alpine3 distro test container.  See https://github.com/ansible/ansible/pull/70946 for the changes to integration tests to accommodate this container.

### CODE REVIEW

**Comment by mattclay** [comment]
@sivel It looks like CI is failing due to issues building the Fedora containers. We'll need to fix those in another PR before CI will pass on this one.

**Comment by sivel** [comment]
No problem. I'm still fixing integration tests for Alpine right yet, so I'm not ready for this anyway.

I'll look into the fedora issue if I make it there before anyone else.

**Comment by samdoran** [comment]
The Fedora image failure was fixed in. #40

**Comment by sivel** [comment]
The tests in https://github.com/ansible/ansible/pull/70946 are fully passing.

Assuming we want this, once we merge this I can update the above PR to start testing against Alpine in CI.

**Pull request merged**
